app/YDSpider/__init__.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from flask import Blueprint

trans = Blueprint('trans', __name__)

from . import views

app/YDSpider/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from flask import render_template, request, jsonify
from YoudaoSpider import MyTranslation
from . import trans
from ..common import check_login, response_messages
from json import loads

@trans.route('/youdao_spider/', methods=['GET', 'POST'])
def youdao_spider():
    if request.method == 'GET':
        context = {
            'user': check_login()
        }

        return render_template('YDSpider/index.html', **context)

    if request.method == 'POST':
        re = {'status': True, 'data': {}}
        data = loads(request.get_data(), encoding='utf-8')

        question = data['data']['question']
        print 'question:' + question
        if question == '':
            re['status'] = False
            response_messages(re, title=u'输入有误', content=u'需要翻译的内容不能为空哦！')
            return jsonify(re)
        else:
            re['data']['answer'] = MyTranslation(question).GetAns()
            print 'answer:' + re['data']['answer']
            return jsonify(re)

app/templates/YDSpider/index.html
{% extends 'index_base.html' %}
{% import '_macros.html' as macros %}

{% block title %}
    我的翻译器
{% endblock %}

{% block user_navbar %}
    {{ macros.add_user_navbar(user) }}
{% endblock %}

{% block new_css %}
    <style>
        .trans-container {
            position: relative;
            top: 40px;
            font-size: 14px;
        }

        .my-trans-text {
            width: 100%;
        }
    </style>
{% endblock %}

{% block new_content %}
    <div class="container trans-container">
        <div class="col-md-6">
            <form method="post">
                <div id="question" class="form-group">
                    <textarea id="user-Q" class="my-trans-text" rows="10" placeholder="请输入需要翻译的内容"></textarea>
                </div>
                <div class="form-group">
                    <button type="button" id="btn-translation" class="btn btn-primary btn-block">立即翻译</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <textarea id="server-A" class="my-trans-text" rows="10" readonly></textarea>
        </div>
    </div>
{% endblock %}

{% block new_js %}
    <script>
        clear_navbar_active();
        $('#btn-translation').click(function () {

            var csrftoken = $('meta[name=csrf-token]').attr('content');

            $.ajax({
                url: '{{ url_for('trans.youdao_spider') }}',
                type: 'POST',
                contentType: "application/json; charset=UTF-8",
                beforeSend: function (xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken)
                    }
                },
                data: JSON.stringify({
                    'data': {
                        'question': $('#user-Q').val()
                    }
                }),
                dataType: 'json',
            }).done(function (data, textStatus) {
                console.log(data);
                if (data['status'] == true) {
                    clear_prompting();
                    $('#server-A').val(data['data']['answer']);
                }
                else {
                    errors = data['data'];
                    $('#server-A').val('');
                    show_message(data);
                }
            }).fail(function (xhr, err) {
                alert('请求失败！');
            });
        });

        $('body').keydown(function () {
            if (event.keyCode == '13' && $('#btn-login').is(':hidden')
                && $('#btn-login').is(':hidden')
                && $('#btn-register').is(':hidden')) {
                $('#btn-translation').click();
            }
        });
    </script>
{% endblock %}

app/templates/YDSpider/youdao_spider.html
{% extends 'index_base.html' %}

{% block title %}
    我的翻译器
{% endblock %}

{% block user_navbar %}
    {% include '_user_navbar.html' %}
{% endblock %}

{% block new_css %}
    <style>
        .trans-container {
            position: relative;
            top: 40px;
            font-size: 14px;
        }

        .my-trans-text {
            width: 100%;
        }
    </style>
{% endblock %}

{% block new_content %}
    <div class="container trans-container">
        <div class="col-md-6">
            <form method="post">
                <div id="question" class="form-group">
                    <textarea id="user-Q" class="my-trans-text" rows="10" placeholder="请输入需要翻译的内容"></textarea>
                </div>
                <div class="form-group">
                    <button type="button" id="btn-translation" class="btn btn-primary btn-block">立即翻译</button>
                </div>
            </form>
        </div>
        <div class="col-md-6">
            <textarea id="server-A" class="my-trans-text" rows="10" readonly></textarea>
        </div>
    </div>
{% endblock %}

{% block new_js %}
    <script>
        clear_navbar_active();
        $('#btn-translation').click(function () {

            var csrftoken = $('meta[name=csrf-token]').attr('content');

            $.ajax({
                url: '{{ url_for('trans.youdao_spider') }}',
                type: 'POST',
                contentType: "application/json; charset=UTF-8",
                beforeSend: function (xhr, settings) {
                    if (!/^(GET|HEAD|OPTIONS|TRACE)$/i.test(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken)
                    }
                },
                data: JSON.stringify({
                    'data': {
                        'question': $('#user-Q').val()
                    }
                }),
                dataType: 'json',
            }).done(function (data, textStatus) {
                console.log(data);
                if (data['status'] == true) {
                    clear_prompting();
                    $('#server-A').val(data['data']['answer']);
                }
                else {
                    errors = data['data'];
                    $('#server-A').val('');
                    show_message(data);
                }
            }).fail(function (xhr, err) {
                alert('请求失败！');
            });
        });

        $('body').keydown(function () {
            if (event.keyCode == '13' && $('#btn-login').is(':hidden')) {
                $('#btn-translation').click();
            }
        });
    </script>
{% endblock %}